name: mol_regexp

on:
  workflow_dispatch:
  push:
    branches: 
    - master
  pull_request:
  schedule:
  - cron: "0 7 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - name: Environment Printer
      uses: managedkaos/print-env@v1.0
    
    - name: Build apps
      uses: hyoo-ru/mam_build@master2
      with:
        package: hyoo/crowd
        modules: lib
    
    - uses: JS-DevTools/npm-publish@v1
      if: ${{ github.ref == 'refs/heads/master' && ( github.event_name == 'push' || github.event_name == 'workflow_dispatch' ) }}
      with:
        token: ${{ secrets.NPM_AUTH_TOKEN }}
        package: ./hyoo/crowd/lib/-/package.json
